apiVersion: v1
kind: ConfigMap
metadata:
  name: egress-policy
  namespace: default
  labels:
    egress-controller: "managed"
data:
  policy.json: |
    {
      "defaultAction": "deny",
      "allowedDestinations": [
        {
          "name": "s3-access",
          "awsService": "s3",
          "regions": ["us-east-1"],
          "ports": [443]
        },
        {
          "name": "onprem-database",
          "cidr": "10.1.100.0/24",
          "ports": [5432, 3306]
        },
        {
          "name": "internal-api",
          "cidr": "10.0.0.0/16",
          "ports": [80, 443]
        }
      ]
    }
