apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-agent
  labels:
    app: egress-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egress-agent
  template:
    metadata:
      labels:
        app: egress-agent
    spec:
      serviceAccountName: egress-agent
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: egress-agent
        image: egress-agent:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: DRY_RUN
          value: "false"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 10
